### ISSUE TITLE
circular dependency (probably bad naming convention)

### ISSUE THREAD

**Issue by gnwong** [AFD-Illinois/pyHARM#2]
When I install either using the yml or in my own conda env, I get the following error when I try to import pyHARM

```
>>> import pyHARM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/codes/afd-illinois/pyHARM/pyHARM/__init__.py", line 3, in <module>
    from .ana.iharm_dump import IharmDump
  File "$HOME/codes/afd-illinois/pyHARM/pyHARM/ana/iharm_dump.py", line 12, in <module>
    import pyHARM.io as io
  File "$HOME/codes/afd-illinois/pyHARM/pyHARM/io/__init__.py", line 5, in <module>
    import pyHARM.io.ilhdf as ilhdf
  File "$HOME/codes/afd-illinois/pyHARM/pyHARM/io/ilhdf.py", line 4, in <module>
    import h5py
  File "/opt/apps/intel19/impi19_0/python3/3.7.0/lib/python3.7/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: cannot import name '_errors' from partially initialized module 'h5py' (most likely due to a circular import) (/opt/apps/intel19/impi19_0/python3/3.7.0/lib/python3.7/site-packages/h5py/__init__.py)
```

In my experience, this normally happens when there are two files with the same name (one to be imported and one in the local directory). I've tried importing pyHARM from different directories (including empty ones) but I always run into this error.

**Comment by gnwong** [comment]
It's not clear whether this is an issue with the dependencies or an id-10t issue with my environment. Closing for now.
